/* ============================================================
   POSTGRES SCHEMA
   Shared by the app (lib/db.js) and the one-off migration script
   (scripts/db-migrate.mjs) so the two can never drift apart.

   ── Why the column names are quoted ──────────────────────────
   Postgres folds unquoted identifiers to lower case, so
   `SELECT brandSlug` returns a column called `brandslug` and
   `row.brandSlug` is silently `undefined` -- blank fields, no error.
   Quoting preserves the camelCase these tables were born with, which
   keeps every row object identical in shape to the SQLite version.
   That's the whole point: 45 files read these objects and none of
   them have to change.

   The cost is that every identifier must stay quoted, forever. All
   SQL lives in lib/content.js and lib/admin-data.js, so that's a
   contained promise to keep.

   ── Types ────────────────────────────────────────────────────
   Columns that held `JSON.stringify(...)` output in TEXT are JSON
   here. The driver hands those back as real objects, which is why
   parseJson() in lib/content.js has to tolerate a non-string.

   `GENERATED BY DEFAULT AS IDENTITY`, not ALWAYS: the migration
   inserts rows with their original ids, and ALWAYS would reject that.
   ============================================================ */

export const SCHEMA_SQL = `
CREATE TABLE IF NOT EXISTS site_settings (
  id            INTEGER PRIMARY KEY CHECK (id = 1),
  company       TEXT,
  tagline       TEXT,
  "heroKicker"  TEXT,
  "heroHeadline" TEXT,
  "heroSub"     TEXT,
  "ctaPrimary"  TEXT,
  "ctaSecondary" TEXT,
  mission       TEXT,
  address       TEXT,
  phone         TEXT,
  email         TEXT,
  stats         JSON,
  -- Singular: a legacy single-video field, superseded by "heroVideos"
  -- but still present in the live data, so it has to come across.
  "heroVideo"   TEXT,
  "heroVideos"  JSON,
  "aboutHeadline" TEXT,
  "aboutValues" JSON,
  "aboutTimeline" JSON
);

CREATE TABLE IF NOT EXISTS brands (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug        TEXT UNIQUE NOT NULL,
  name        TEXT,
  logo        TEXT,
  focus       TEXT,
  blurb       TEXT,
  "heroImage" TEXT,
  "heroVideo" TEXT
);

CREATE TABLE IF NOT EXISTS products (
  id                   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "brandSlug"          TEXT NOT NULL,
  slug                 TEXT NOT NULL,
  name                 TEXT,
  model                TEXT,
  "shortDescription"   TEXT,
  description          TEXT,
  image                TEXT,
  gallery              JSON,
  specs                JSON,
  "specSheet"          TEXT,
  "specSheetVariants"  JSON,
  category             TEXT,
  tag                  TEXT,
  UNIQUE ("brandSlug", slug)
);

CREATE TABLE IF NOT EXISTS solutions (
  id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug           TEXT UNIQUE NOT NULL,
  name           TEXT,
  logo           TEXT,
  tag            TEXT,
  summary        TEXT,
  description    TEXT,
  features       JSON,
  modules        JSON,
  advantages     JSON,
  "hardwareUsed" JSON,
  visual         TEXT,
  "heroVideo"    TEXT
);

CREATE TABLE IF NOT EXISTS industrial_solutions (
  id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug           TEXT UNIQUE NOT NULL,
  name           TEXT,
  logo           TEXT,
  tag            TEXT,
  summary        TEXT,
  description    TEXT,
  features       JSON,
  modules        JSON,
  advantages     JSON,
  "hardwareUsed" JSON,
  visual         TEXT,
  -- Present only on this table, not on solutions. Added by a later
  -- ALTER TABLE that never made it into the base CREATE in db.js.
  video          TEXT,
  "heroVideo"    TEXT
);

CREATE TABLE IF NOT EXISTS industries (
  id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug           TEXT UNIQUE NOT NULL,
  name           TEXT,
  logo           TEXT,
  tag            TEXT,
  summary        TEXT,
  description    TEXT,
  features       JSON,
  modules        JSON,
  advantages     JSON,
  "hardwareUsed" JSON,
  clients        JSON,
  visual         TEXT,
  "heroVideo"    TEXT
);

CREATE TABLE IF NOT EXISTS hardware_categories (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug        TEXT UNIQUE NOT NULL,
  category    TEXT,
  name        TEXT,
  description TEXT,
  image       TEXT,
  chips       JSON,
  specs       JSON,
  "specSheet" TEXT
);

CREATE TABLE IF NOT EXISTS clients (
  id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT,
  logo TEXT
);

CREATE TABLE IF NOT EXISTS posts (
  id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug     TEXT UNIQUE NOT NULL,
  title    TEXT,
  category TEXT,
  date     TEXT,
  excerpt  TEXT,
  image    TEXT,
  body     TEXT
);

CREATE TABLE IF NOT EXISTS leads (
  id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name  TEXT,
  email TEXT,
  phone TEXT,
  msg   TEXT,
  type  TEXT DEFAULT 'contact',
  at    TEXT
);

CREATE TABLE IF NOT EXISTS admins (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email         TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  created_at    TEXT NOT NULL
);
`

/* Which columns hold JSON. The migration reads these out of SQLite as
   TEXT and must hand them to Postgres as JSON, not as a quoted string. */
export const JSON_COLUMNS = {
  site_settings: ['stats', 'heroVideos', 'aboutValues', 'aboutTimeline'],
  products: ['gallery', 'specs', 'specSheetVariants'],
  solutions: ['features', 'modules', 'advantages', 'hardwareUsed'],
  industrial_solutions: ['features', 'modules', 'advantages', 'hardwareUsed'],
  industries: ['features', 'modules', 'advantages', 'hardwareUsed', 'clients'],
  hardware_categories: ['chips', 'specs'],
  brands: [],
  clients: [],
  posts: [],
  leads: [],
  admins: [],
}

/* Copy order. No foreign keys exist between these tables (products
   reference a brand by slug string, not by id), so order is only about
   readability -- but keep site_settings first so a partial run still
   leaves the site renderable. */
export const TABLES = [
  'site_settings',
  'brands',
  'products',
  'solutions',
  'industrial_solutions',
  'industries',
  'hardware_categories',
  'clients',
  'posts',
  'leads',
  'admins',
]
